# -*- coding: utf-8 -*-
"""F_Prototypical_MAIN_KAN_KDwith_EMA_CIC_IDS_Dataset__With_confusion_Matrix(256,128)(128).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xEezA7zRZY0Eo3yvlcgdr27F8WMKBCJy
"""

# ======================== IMPORTS ========================
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import classification_report, accuracy_score, f1_score, confusion_matrix
import torch.nn.functional as F
import matplotlib.pyplot as plt
import seaborn as sns
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import numpy as np
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, f1_score, precision_score, recall_score
from torch.utils.data import DataLoader, TensorDataset
import seaborn as sns
import matplotlib.pyplot as plt
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print("Using device:", DEVICE)

# ================================
# ---- DATA PREPROCESSING ----
# ================================
df = pd.concat(map(pd.read_csv, [
    '/content/Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv',
    '/content/Friday-WorkingHours-Afternoon-PortScan.pcap_ISCX.csv',
    '/content/Friday-WorkingHours-Morning.pcap_ISCX.csv',
    '/content/Monday-WorkingHours.pcap_ISCX.csv',
    '/content/Thursday-WorkingHours-Afternoon-Infilteration.pcap_ISCX.csv',
    '/content/Thursday-WorkingHours-Morning-WebAttacks.pcap_ISCX.csv',
    '/content/Tuesday-WorkingHours.pcap_ISCX.csv',
    '/content/Wednesday-workingHours.pcap_ISCX.csv'
]), ignore_index=True)

print(df)
col_name_list = list(df.columns)
print("col_name_list = ", col_name_list)
size_col_name_list = len(col_name_list)
print("size_col_name_list = ", size_col_name_list)


df.replace([np.inf, -np.inf], np.nan, inplace=True)
df.fillna(0, inplace=True)
print(df)

print(df[' Label'].value_counts())

label_encoder = LabelEncoder()
df[' Label'] = label_encoder.fit_transform(df[' Label'])
attack_names = [str(x) for x in label_encoder.classes_]
print("Classes:", attack_names)

X = df.drop([' Label'], axis=1).values
y = df[' Label'].values

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

class TabularDataset(Dataset):
    def __init__(self, X, y):
        self.X = torch.tensor(X, dtype=torch.float32)
        self.y = torch.tensor(y, dtype=torch.long)
    def __len__(self):
        return self.X.size(0)
    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]

train_ds = TabularDataset(X_train, y_train)
test_ds  = TabularDataset(X_test,  y_test)

import torch
import torch.nn.functional as F
import math


class KANLinear(torch.nn.Module):
    def __init__(
        self,
        in_features,
        out_features,
        grid_size=5,
        spline_order=3,
        scale_noise=0.1,
        scale_base=1.0,
        scale_spline=1.0,
        enable_standalone_scale_spline=True,
        base_activation=torch.nn.SiLU,
        grid_eps=0.02,
        grid_range=[-1, 1],
    ):
        super(KANLinear, self).__init__()
        self.in_features = in_features
        self.out_features = out_features
        self.grid_size = grid_size
        self.spline_order = spline_order

        h = (grid_range[1] - grid_range[0]) / grid_size
        grid = (
            (
                torch.arange(-spline_order, grid_size + spline_order + 1) * h
                + grid_range[0]
            )
            .expand(in_features, -1)
            .contiguous()
        )
        self.register_buffer("grid", grid)

        self.base_weight = torch.nn.Parameter(torch.Tensor(out_features, in_features))
        self.spline_weight = torch.nn.Parameter(
            torch.Tensor(out_features, in_features, grid_size + spline_order)
        )
        if enable_standalone_scale_spline:
            self.spline_scaler = torch.nn.Parameter(
                torch.Tensor(out_features, in_features)
            )

        self.scale_noise = scale_noise
        self.scale_base = scale_base
        self.scale_spline = scale_spline
        self.enable_standalone_scale_spline = enable_standalone_scale_spline
        self.base_activation = base_activation()
        self.grid_eps = grid_eps

        self.reset_parameters()

    def reset_parameters(self):
        torch.nn.init.kaiming_uniform_(self.base_weight, a=math.sqrt(5) * self.scale_base)
        with torch.no_grad():
            noise = (
                (
                    torch.rand(self.grid_size + 1, self.in_features, self.out_features)
                    - 1 / 2
                )
                * self.scale_noise
                / self.grid_size
            )
            self.spline_weight.data.copy_(
                (self.scale_spline if not self.enable_standalone_scale_spline else 1.0)
                * self.curve2coeff(
                    self.grid.T[self.spline_order : -self.spline_order],
                    noise,
                )
            )
            if self.enable_standalone_scale_spline:
                # torch.nn.init.constant_(self.spline_scaler, self.scale_spline)
                torch.nn.init.kaiming_uniform_(self.spline_scaler, a=math.sqrt(5) * self.scale_spline)

    def b_splines(self, x: torch.Tensor):
        """
        Compute the B-spline bases for the given input tensor.

        Args:
            x (torch.Tensor): Input tensor of shape (batch_size, in_features).

        Returns:
            torch.Tensor: B-spline bases tensor of shape (batch_size, in_features, grid_size + spline_order).
        """
        assert x.dim() == 2 and x.size(1) == self.in_features

        grid: torch.Tensor = (
            self.grid
        )  # (in_features, grid_size + 2 * spline_order + 1)
        x = x.unsqueeze(-1)
        bases = ((x >= grid[:, :-1]) & (x < grid[:, 1:])).to(x.dtype)
        for k in range(1, self.spline_order + 1):
            bases = (
                (x - grid[:, : -(k + 1)])
                / (grid[:, k:-1] - grid[:, : -(k + 1)])
                * bases[:, :, :-1]
            ) + (
                (grid[:, k + 1 :] - x)
                / (grid[:, k + 1 :] - grid[:, 1:(-k)])
                * bases[:, :, 1:]
            )

        assert bases.size() == (
            x.size(0),
            self.in_features,
            self.grid_size + self.spline_order,
        )
        return bases.contiguous()

    def curve2coeff(self, x: torch.Tensor, y: torch.Tensor):
        """
        Compute the coefficients of the curve that interpolates the given points.

        Args:
            x (torch.Tensor): Input tensor of shape (batch_size, in_features).
            y (torch.Tensor): Output tensor of shape (batch_size, in_features, out_features).

        Returns:
            torch.Tensor: Coefficients tensor of shape (out_features, in_features, grid_size + spline_order).
        """
        assert x.dim() == 2 and x.size(1) == self.in_features
        assert y.size() == (x.size(0), self.in_features, self.out_features)

        A = self.b_splines(x).transpose(
            0, 1
        )  # (in_features, batch_size, grid_size + spline_order)
        B = y.transpose(0, 1)  # (in_features, batch_size, out_features)
        solution = torch.linalg.lstsq(
            A, B
        ).solution  # (in_features, grid_size + spline_order, out_features)
        result = solution.permute(
            2, 0, 1
        )  # (out_features, in_features, grid_size + spline_order)

        assert result.size() == (
            self.out_features,
            self.in_features,
            self.grid_size + self.spline_order,
        )
        return result.contiguous()

    @property
    def scaled_spline_weight(self):
        return self.spline_weight * (
            self.spline_scaler.unsqueeze(-1)
            if self.enable_standalone_scale_spline
            else 1.0
        )

    def forward(self, x: torch.Tensor):
        assert x.size(-1) == self.in_features
        original_shape = x.shape
        x = x.reshape(-1, self.in_features)

        base_output = F.linear(self.base_activation(x), self.base_weight)
        spline_output = F.linear(
            self.b_splines(x).view(x.size(0), -1),
            self.scaled_spline_weight.view(self.out_features, -1),
        )
        output = base_output + spline_output

        output = output.reshape(*original_shape[:-1], self.out_features)
        return output

    @torch.no_grad()
    def update_grid(self, x: torch.Tensor, margin=0.01):
        assert x.dim() == 2 and x.size(1) == self.in_features
        batch = x.size(0)

        splines = self.b_splines(x)  # (batch, in, coeff)
        splines = splines.permute(1, 0, 2)  # (in, batch, coeff)
        orig_coeff = self.scaled_spline_weight  # (out, in, coeff)
        orig_coeff = orig_coeff.permute(1, 2, 0)  # (in, coeff, out)
        unreduced_spline_output = torch.bmm(splines, orig_coeff)  # (in, batch, out)
        unreduced_spline_output = unreduced_spline_output.permute(
            1, 0, 2
        )  # (batch, in, out)

        # sort each channel individually to collect data distribution
        x_sorted = torch.sort(x, dim=0)[0]
        grid_adaptive = x_sorted[
            torch.linspace(
                0, batch - 1, self.grid_size + 1, dtype=torch.int64, device=x.device
            )
        ]

        uniform_step = (x_sorted[-1] - x_sorted[0] + 2 * margin) / self.grid_size
        grid_uniform = (
            torch.arange(
                self.grid_size + 1, dtype=torch.float32, device=x.device
            ).unsqueeze(1)
            * uniform_step
            + x_sorted[0]
            - margin
        )

        grid = self.grid_eps * grid_uniform + (1 - self.grid_eps) * grid_adaptive
        grid = torch.concatenate(
            [
                grid[:1]
                - uniform_step
                * torch.arange(self.spline_order, 0, -1, device=x.device).unsqueeze(1),
                grid,
                grid[-1:]
                + uniform_step
                * torch.arange(1, self.spline_order + 1, device=x.device).unsqueeze(1),
            ],
            dim=0,
        )

        self.grid.copy_(grid.T)
        self.spline_weight.data.copy_(self.curve2coeff(x, unreduced_spline_output))

    def regularization_loss(self, regularize_activation=1.0, regularize_entropy=1.0):
        """
        Compute the regularization loss.

        This is a dumb simulation of the original L1 regularization as stated in the
        paper, since the original one requires computing absolutes and entropy from the
        expanded (batch, in_features, out_features) intermediate tensor, which is hidden
        behind the F.linear function if we want an memory efficient implementation.

        The L1 regularization is now computed as mean absolute value of the spline
        weights. The authors implementation also includes this term in addition to the
        sample-based regularization.
        """
        l1_fake = self.spline_weight.abs().mean(-1)
        regularization_loss_activation = l1_fake.sum()
        p = l1_fake / regularization_loss_activation
        regularization_loss_entropy = -torch.sum(p * p.log())
        return (
            regularize_activation * regularization_loss_activation
            + regularize_entropy * regularization_loss_entropy
        )


class KAN(torch.nn.Module):
    def __init__(
        self,
        layers_hidden,
        grid_size=5,
        spline_order=3,
        scale_noise=0.1,
        scale_base=1.0,
        scale_spline=1.0,
        base_activation=torch.nn.SiLU,
        grid_eps=0.02,
        grid_range=[-1, 1],
    ):
        super(KAN, self).__init__()
        self.grid_size = grid_size
        self.spline_order = spline_order

        self.layers = torch.nn.ModuleList()
        for in_features, out_features in zip(layers_hidden, layers_hidden[1:]):
            self.layers.append(
                KANLinear(
                    in_features,
                    out_features,
                    grid_size=grid_size,
                    spline_order=spline_order,
                    scale_noise=scale_noise,
                    scale_base=scale_base,
                    scale_spline=scale_spline,
                    base_activation=base_activation,
                    grid_eps=grid_eps,
                    grid_range=grid_range,
                )
            )

    def forward(self, x: torch.Tensor, update_grid=False):
        for layer in self.layers:
            if update_grid:
                layer.update_grid(x)
            x = layer(x)
        return x

    def regularization_loss(self, regularize_activation=1.0, regularize_entropy=1.0):
        return sum(
            layer.regularization_loss(regularize_activation, regularize_entropy)
            for layer in self.layers
        )

# ============= Efficient KAN ProtoNet Model =============
class KANEncoder(nn.Module):
    def __init__(self, input_dim, hidden_dims, out_dim=128):
        super().__init__()
        layers_hidden = [input_dim] + hidden_dims + [out_dim]
        self.kan = KAN(
            layers_hidden=layers_hidden,
            grid_size=5,
            spline_order=3,
            scale_noise=0.1,
            scale_base=1.0,
            scale_spline=1.0,
            base_activation=torch.nn.SiLU,
            grid_eps=0.02,
            grid_range=[-1, 1],
        )
    def forward(self, x):
        return self.kan(x)

"""#ProtoKAN"""

class ProtonetKAN(nn.Module):
    def __init__(self, encoder, n_classes):
        super().__init__()
        self.encoder = encoder
        self.n_classes = n_classes

    def compute_prototypes(self, embeddings, labels):
        prototypes = []
        for c in range(self.n_classes):
            mask = (labels == c)
            emb = embeddings[mask]
            if emb.size(0) == 0:
                prototypes.append(torch.zeros(embeddings.size(1), device=embeddings.device))
            else:
                prototypes.append(emb.mean(dim=0))
        return torch.stack(prototypes)

    def forward(self, x, labels):
        embeddings = self.encoder(x)
        prototypes = self.compute_prototypes(embeddings, labels)
        dists = ((embeddings.unsqueeze(1) - prototypes.unsqueeze(0)) ** 2).sum(-1)
        return -dists  # logits

"""#TEACHERS - CUDA"""

def train_teacher(model, train_loader, optimizer, n_epochs=30, device=DEVICE, name="Teacher"):
    model.train()
    for epoch in range(1, n_epochs + 1):
        losses, all_preds, all_targets = [], [], []
        for xb, yb in train_loader:
            xb, yb = xb.to(device), yb.to(device)
            logits = model(xb, yb)
            loss = F.cross_entropy(logits, yb)
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            losses.append(loss.item())
            preds = logits.softmax(dim=1).argmax(dim=1)
            all_preds.append(preds.cpu().numpy())
            all_targets.append(yb.cpu().numpy())

        epoch_acc = accuracy_score(np.concatenate(all_targets), np.concatenate(all_preds))
        print(f'[{name}] Epoch {epoch:02d} | Loss: {np.mean(losses):.4f} | Acc: {epoch_acc:.4f}')

"""#STUDENT - CPU(FREE GOOGLE COLAB RESOURCES)"""

def distill_student_multi_teacher(
    teacher1, teacher2, student, loader, optimizer,
    n_epochs=50, device='cpu', temperature=4.0, alpha=0.5
):
    """
    alpha = weight on hard CE; (1-alpha) on KD. (If you want logit-only, set alpha=0.0)
    """
    T = temperature
    student.train()
    for _ in range(n_epochs):
        for xb, yb in loader:
            xb, yb = xb.to(device), yb.to(device)
            optimizer.zero_grad()

            with torch.no_grad():
                t1 = teacher1(xb, yb)
                t2 = teacher2(xb, yb)
                soft_t = 0.5*F.softmax(t1/T, dim=1) + 0.5*F.softmax(t2/T, dim=1)

            s = student(xb, yb)

            kd = F.kl_div(
                F.log_softmax(s/T, dim=1),
                soft_t,
                reduction="batchmean"
            ) * (T*T)

            hard = F.cross_entropy(s, yb)
            loss = (1 - alpha) * kd + alpha * hard

            loss.backward()
            optimizer.step()

# ============= MAIN PIPELINE =============
DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'
BATCH_SIZE = 256
n_classes = len(np.unique(y_train))

train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True)
test_loader  = DataLoader(test_ds,  batch_size=BATCH_SIZE)

# Teachers (high capacity)
teacher1 = ProtonetKAN(
    KANEncoder(X_train.shape[1], [256, 256, 128], 256),
    n_classes
).to(DEVICE)
optimizer_teacher1 = optim.Adam(teacher1.parameters(), lr=1e-3)

teacher2 = ProtonetKAN(
    KANEncoder(X_train.shape[1], [256, 128, 256], 256),
    n_classes
).to(DEVICE)
optimizer_teacher2 = optim.Adam(teacher2.parameters(), lr=1e-3)

print("\nTraining Teacher 1 …")
train_teacher(teacher1, train_loader, optimizer_teacher1, n_epochs=30, name="Teacher1")

print("\nTraining Teacher 2 …")
train_teacher(teacher2, train_loader, optimizer_teacher2, n_epochs=30, name="Teacher2")

# Freeze teachers for KD
for p in teacher1.parameters(): p.requires_grad = False
for p in teacher2.parameters(): p.requires_grad = False
teacher1.eval(); teacher2.eval()

def make_cosine_warmup(optimizer, num_epochs, warmup_ratio=0.1):
    warm = max(1, int(warmup_ratio * num_epochs))
    def lr_lambda(epoch):
        if epoch < warm:
            return float(epoch + 1) / float(warm)
        prog = (epoch - warm) / max(1, (num_epochs - warm))
        return 0.5 * (1.0 + math.cos(math.pi * prog))
    return torch.optim.lr_scheduler.LambdaLR(optimizer, lr_lambda)

class ModelEMA:
    def __init__(self, model, decay=0.999, device=None):
        self.decay = decay
        self.shadow = {}
        self.backup = {}
        for name, param in model.named_parameters():
            if param.requires_grad:
                self.shadow[name] = param.data.clone()
        self.device = device

    @torch.no_grad()
    def update(self, model):
        for name, param in model.named_parameters():
            if param.requires_grad:
                self.shadow[name] = self.decay * self.shadow[name] + (1.0 - self.decay) * param.data

    @torch.no_grad()
    def apply_shadow(self, model):
        self.backup = {}
        for n, p in model.named_parameters():
            if p.requires_grad:
                self.backup[n] = p.data.clone()
                p.data.copy_(self.shadow[n])

    @torch.no_grad()
    def restore(self, model):
        for n, p in model.named_parameters():
            if n in self.backup and p.requires_grad:
                p.data.copy_(self.backup[n])
        self.backup = {}

import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import torch
from sklearn.metrics import multilabel_confusion_matrix
import pandas as pd

def tp_tn_fp_fn_tables(y_true, y_pred, class_names):
    mcm = multilabel_confusion_matrix(y_true, y_pred)
    rows = []
    for idx, cls in enumerate(class_names):
        tn, fp, fn, tp = mcm[idx].ravel()
        rows.append([cls, tp, tn, fp, fn])

    df = pd.DataFrame(rows, columns=["Class", "TP", "TN", "FP", "FN"])
    print("\n=== TP / TN / FP / FN per class ===")
    print(df.to_string(index=False))
    return df

@torch.no_grad()
def evaluate_full(model, loader, name="Model", class_names=None, device=None):
    model.eval()
    if device is None:
        device = next(model.parameters()).device

    y_true, y_pred = [], []
    for xb, yb in loader:
        xb, yb = xb.to(device), yb.to(device)
        try:
            logits = model(xb, yb)
        except TypeError:
            logits = model(xb)
        y_true.append(yb.cpu().numpy())
        y_pred.append(logits.softmax(1).argmax(1).cpu().numpy())

    y_true = np.concatenate(y_true)
    y_pred = np.concatenate(y_pred)

    # Fix class order to match names on both axes
    if class_names is not None:
        labels_order = np.arange(len(class_names))
        tick_names   = class_names
    else:
        labels_order = np.unique(np.concatenate([y_true, y_pred]))
        tick_names   = [str(i) for i in labels_order]

    cm  = confusion_matrix(y_true, y_pred, labels=labels_order)
    acc = accuracy_score(y_true, y_pred)

    print(f"\n=== {name} ===")
    print(f"Accuracy: {acc:.4f}")
    print(
        classification_report(
            y_true, y_pred,
            labels=labels_order,
            target_names=tick_names,
            digits=4
        )
    )

    # compute F1 per class
    report = classification_report(
        y_true, y_pred,
        labels=labels_order,
        target_names=tick_names,
        output_dict=True,
        digits=4
    )
    f1_per_class = [report.get(n, {}).get("f1-score", 0.0) for n in tick_names]

    # build new y-ticks with F1
    ytick = [f"{cls}\nF1={f1_per_class[i]:.2f}" for i, cls in enumerate(tick_names)]

    # === heatmap ===
    plt.figure(figsize=(14, 10))
    ax = sns.heatmap(
        cm, annot=True, fmt='d', cmap='Blues',
        xticklabels=tick_names, yticklabels=ytick   # <-- tweaked here
    )
    ax.set_title(f"Confusion Matrix — {name}")
    ax.set_xlabel("Predicted")
    ax.set_ylabel("True (with F1)")
    plt.xticks(rotation=90, ha='center')
    plt.yticks(rotation=0)
    plt.tight_layout()
    plt.show()

    plt.figure(figsize=(8,5))

    plt.plot(range(1, len(total_kd_losses)+1), total_kd_losses,
         color='tab:blue', marker='o', linewidth=2, label='KD Training Loss')
    plt.title("Convergence Curve — Knowledge Distillation (Student)")
    plt.xlabel("Epochs")
    plt.ylabel("Average Training Loss")
    plt.grid(True, linestyle='--', alpha=0.6)
    plt.legend()
    plt.tight_layout()
    plt.show()

    # TP/TN/FP/FN table
    tp_tn_fp_fn_tables(y_true, y_pred, tick_names)

    return acc

# Student (lightweight)
student = ProtonetKAN(
    KANEncoder(X_train.shape[1], [256, 128], 128),
    n_classes
).to(DEVICE)

# --- Student + KD (evaluates every 10 epochs) ---

KD_EPOCHS    = 50
EVAL_EVERY   = 10   # <<<<<<<<<< evaluate RAW & EMA every N epochs
BASE_LR      = 1e-3
WEIGHT_DECAY = 5e-4
WARMUP_RATIO = 0.1
EMA_DECAY    = 0.999
KD_T         = 4.0
KD_ALPHA     = 0.5

opt_student = optim.AdamW(student.parameters(), lr=BASE_LR, weight_decay=WEIGHT_DECAY)
sch_student = make_cosine_warmup(opt_student, num_epochs=KD_EPOCHS, warmup_ratio=WARMUP_RATIO)
ema = ModelEMA(student, decay=EMA_DECAY, device=DEVICE)

# Monkey-patch optimizer.step to update EMA automatically
orig_step = opt_student.step
def step_with_ema(*args, **kwargs):
    out = orig_step(*args, **kwargs)
    ema.update(student)
    return out
opt_student.step = step_with_ema

best_acc_raw = 0.0
best_acc_ema = 0.0
best_state_raw, best_state_ema = None, None
total_kd_losses = []
for epoch in range(1, KD_EPOCHS + 1):
    student.train()
    batch_losses = []
    for xb, yb in train_loader:
        xb, yb = xb.to(DEVICE), yb.to(DEVICE)
        opt_student.zero_grad()

        with torch.no_grad():
            t1 = teacher1(xb, yb)
            t2 = teacher2(xb, yb)
            soft_t = 0.5 * F.softmax(t1 / KD_T, dim=1) + 0.5 * F.softmax(t2 / KD_T, dim=1)

        s = student(xb, yb)
        kd   = F.kl_div(F.log_softmax(s / KD_T, dim=1), soft_t, reduction="batchmean") * (KD_T * KD_T)
        hard = F.cross_entropy(s, yb)
        loss = (1 - KD_ALPHA) * kd + KD_ALPHA * hard

        loss.backward()
        sch_student.step()
        opt_student.step()
        batch_losses.append(loss.item())
        with torch.no_grad():
          epoch_loss = np.mean(batch_losses)
          total_kd_losses.append(epoch_loss)

    # ---------- evaluate only every N epochs ----------
    if (epoch % EVAL_EVERY == 0) or (epoch == KD_EPOCHS):
        acc_raw = evaluate_full(student, test_loader, name=f"Student RAW (epoch {epoch})",
                                class_names=attack_names, device=DEVICE)
        if acc_raw > best_acc_raw:
            best_acc_raw = acc_raw
            best_state_raw = {k: v.detach().cpu().clone() for k, v in student.state_dict().items()}

        ema.apply_shadow(student)
        acc_ema = evaluate_full(student, test_loader, name=f"Student EMA (epoch {epoch})",
                                class_names=attack_names, device=DEVICE)
        if acc_ema > best_acc_ema:
            best_acc_ema = acc_ema
            best_state_ema = {k: v.detach().cpu().clone() for k, v in student.state_dict().items()}
        ema.restore(student)
# ------------------------------------------------------

# Load the better of RAW/EMA
final_state = best_state_ema if best_state_ema is not None else best_state_raw
if final_state is not None:
    student.load_state_dict(final_state)
print(f"\n[Student KD] Loaded best {'EMA' if best_state_ema is not None else 'RAW'} weights.")

# Final evaluation (names on axes & report)
final_acc = evaluate_full(student, test_loader, name="Knowledge Distilled Student ProtoKAN Model Confusion Matrix with Per-Class F1-score", class_names=attack_names, device=DEVICE)
print(f"\n>>> MAIN Student Accuracy: {final_acc*100:.2f}%")

# ===================== STUDENT EFFICIENCY PROOF (PRINT-ONLY) =====================
import time, torch

def param_stats(model):
    total = sum(p.numel() for p in model.parameters())
    trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
    total_bytes = sum(p.nelement() * p.element_size() for p in model.parameters())
    size_mb = total_bytes / 1e6
    bits = (total_bytes / max(total, 1)) * 8
    return dict(total=total, trainable=trainable, size_mb=size_mb, bits=bits)

def forward_any(model, xb, n_classes):
    with torch.no_grad():
        try:
            return model(xb)                # classifier-style
        except TypeError:
            yb_dummy = torch.zeros(xb.size(0), dtype=torch.long, device=xb.device)
            return model(xb, yb_dummy)      # ProtoNetKAN-style

# 1) PARAMS & MODEL SIZE
t1 = param_stats(teacher1)
t2 = param_stats(teacher2)
stu = param_stats(student)

print("\n=== Model Parameter & Size (ALL params) ===")
print(f"Teacher 1 : params={t1['total']:,} (trainable={t1['trainable']:,}) | size={t1['size_mb']:.2f} MB | ~{t1['bits']:.0f}-bit")
print(f"Teacher 2 : params={t2['total']:,} (trainable={t2['trainable']:,}) | size={t2['size_mb']:.2f} MB | ~{t2['bits']:.0f}-bit")
print(f"Student   : params={stu['total']:,} (trainable={stu['trainable']:,}) | size={stu['size_mb']:.2f} MB | ~{stu['bits']:.0f}-bit")

avg_teacher_params = (t1["total"] + t2["total"]) / 2 if (t1["total"] and t2["total"]) else (t1["total"] or t2["total"])
if avg_teacher_params:
    comp = stu["total"] / avg_teacher_params
    print(f"Compression (Student / Avg Teacher): {comp:.3f}×")
else:
    print("Compression: N/A (teacher param count unavailable)")

# 2) LATENCY / THROUGHPUT
student.eval()
xb_real, _ = next(iter(train_loader))
xb_real = xb_real.to(DEVICE)
B = xb_real.size(0)

# Warmup
for _ in range(10): forward_any(student, xb_real, n_classes)
if DEVICE == "cuda": torch.cuda.synchronize()

# Timed runs
iters = 50
t0 = time.time()
for _ in range(iters): forward_any(student, xb_real, n_classes)
if DEVICE == "cuda": torch.cuda.synchronize()
t1 = time.time()

batch_ms = (t1 - t0) / iters * 1000.0
per_sample_ms = batch_ms / B
throughput = (B * iters) / (t1 - t0)

print("\n=== Inference Speed (Student) ===")
print(f"Batch size: {B}")
print(f"Latency: {batch_ms:.3f} ms / batch   |  {per_sample_ms:.3f} ms / sample")
print(f"Throughput: {throughput:,.1f} samples/sec")

# 3) PEAK MEMORY (single forward)
if DEVICE == "cuda":
    torch.cuda.reset_peak_memory_stats()
with torch.no_grad():
    _ = forward_any(student, xb_real, n_classes)
if DEVICE == "cuda":
    torch.cuda.synchronize()
    peak_mb = torch.cuda.max_memory_allocated() / 1e6
    print(f"Peak CUDA memory (single forward): {peak_mb:.2f} MB")

# 4) COMMUNICATION COST ESTIMATE for KD (logit-level; per batch & per epoch)
with torch.no_grad():
    logits = forward_any(teacher1, xb_real, n_classes)  # teacher logits dtype tells bytes/elem
bytes_per_elem = logits.element_size()                  # e.g., FP32=4, FP16=2
C = logits.size(1)                                      # number of classes
logit_bytes_per_batch = B * C * bytes_per_elem
num_batches_per_epoch = len(train_loader)
down_per_epoch = logit_bytes_per_batch * num_batches_per_epoch  # teacher->student

def _fmt_bytes(n):
    units = ["B","KB","MB","GB"]
    i = 0
    while n >= 1024 and i < len(units)-1:
        n /= 1024.0; i += 1
    return f"{n:.2f} {units[i]}"

print("\n=== Communication Cost (KD, teacher logits → student) ===")
print(f"Per batch (downlink): {_fmt_bytes(logit_bytes_per_batch)}  [B={B}, C={C}, dtype={bytes_per_elem*8}-bit]")
print(f"Per epoch (downlink): {_fmt_bytes(down_per_epoch)}  (× {num_batches_per_epoch} batches)")

# 5) SHORT PLAIN-ENGLISH SUMMARY
summary = []
if avg_teacher_params:
    summary.append(f"Student has {comp:.2f}× the params of the average teacher (i.e., {(1/comp):.2f}× smaller).")
summary.append(f"Student runs at ~{per_sample_ms:.3f} ms/sample (batch={B}), achieving ~{throughput:,.0f} samples/s.")
summary.append(f"KD communication uses only class logits: {_fmt_bytes(logit_bytes_per_batch)} per batch, "
               f"{_fmt_bytes(down_per_epoch)} per epoch (dtype {bytes_per_elem*8}-bit).")
print("• " + "\n• ".join(summary))

import time, torch, numpy as np
import matplotlib.pyplot as plt

# ---- helpers ----
def forward_any(model, xb, n_classes):
    with torch.no_grad():
        try:
            return model(xb)
        except TypeError:
            yb_dummy = torch.zeros(xb.size(0), dtype=torch.long, device=xb.device)
            return model(xb, yb_dummy)

def param_stats(model):
    total = sum(p.numel() for p in model.parameters())
    total_bytes = sum(p.nelement() * p.element_size() for p in model.parameters())
    size_mb = total_bytes / 1e6
    return total, size_mb

def time_model(model, xb, n_classes, iters=50, device="cuda"):
    model.eval()
    for _ in range(10): forward_any(model, xb, n_classes)
    if device == "cuda": torch.cuda.synchronize()
    t0 = time.time()
    for _ in range(iters): forward_any(model, xb, n_classes)
    if device == "cuda": torch.cuda.synchronize()
    t1 = time.time()
    return (t1 - t0) / iters * 1000.0  # ms/batch

# ---- use a real batch ----
xb_real, _ = next(iter(train_loader))
xb_real = xb_real.to(DEVICE)
B = xb_real.size(0)

# ---- collect stats ----
names, params_m, size_mb, latency_ms, comm_kb = [], [], [], [], []
models = []
if "teacher1" in globals(): models.append(("Teacher ProtoKAN(Server) 1", teacher1))
if "teacher2" in globals(): models.append(("Teacher ProtoKAN(Server) 2", teacher2))
models.append(("Student ProtoKAN(IoT)", student))

for name, model in models:
    pcount, psize = param_stats(model)
    names.append(name)
    params_m.append(pcount / 1e6)
    size_mb.append(psize)
    ms = time_model(model, xb_real, n_classes, iters=50, device=("cuda" if DEVICE=="cuda" else "cpu"))
    latency_ms.append(ms)
    with torch.no_grad():
        logits = forward_any(model, xb_real, n_classes)
        bytes_per_elem = logits.element_size()
        C = logits.size(1)
        kb = (B * C * bytes_per_elem) / 1024.0
        comm_kb.append(kb)

# ===================== BIGGER FIGURE SETTINGS =====================
plt.rcParams.update({
    "font.size": 14,       # bigger base font
    "axes.titlesize": 16,
    "axes.labelsize": 14,
    "xtick.labelsize": 13,
    "ytick.labelsize": 13,
    "legend.fontsize": 13,
    "figure.dpi": 130       # higher resolution for exports
})

# ===================== FIXED LABEL POSITION (numbers stay on bars) =====================

fig, axes = plt.subplots(1, 3, figsize=(22, 7))  # same large figure
bar_colors = ["#1f77b4", "#2ca02c", "#ff7f0e"]
titles = [
    "Parameters (M)",
    f"Latency (ms / batch={B})",
    "KD Communication (KB / batch)"
]
data_sets = [params_m, latency_ms, comm_kb]
ylabels = ["Millions", "ms / batch", "KB / batch"]

for idx, ax in enumerate(axes):
    values = data_sets[idx]
    ax.bar(names, values, color=bar_colors[idx])

    ax.set_title(titles[idx], pad=15, weight='bold')
    ax.set_ylabel(ylabels[idx])

    # compute the offset so numbers sit inside or right above the bar nicely
    for i, v in enumerate(values):
        # if the bar is tall, place text a bit below the top
        y_offset = v * 0.015 if v > 1 else 0.02
        ax.text(
            i, v - y_offset, f"{v:.2f}",
            ha="center", va="top", fontsize=13, color="white", fontweight="bold"
        )

    ax.grid(True, linestyle="--", alpha=0.4)
    ax.tick_params(axis='x', labelsize=13, pad=2)
    for label in ax.get_xticklabels():
        label.set_rotation(90)
        label.set_ha('right')

plt.tight_layout(pad=3.0, w_pad=3.0, h_pad=2.5)
plt.show()